 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/ranks", type: :request do
  
  # Rank. As you add validations to Rank, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Rank.create! valid_attributes
      get ranks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      rank = Rank.create! valid_attributes
      get rank_url(rank)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_rank_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      rank = Rank.create! valid_attributes
      get edit_rank_url(rank)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Rank" do
        expect {
          post ranks_url, params: { rank: valid_attributes }
        }.to change(Rank, :count).by(1)
      end

      it "redirects to the created rank" do
        post ranks_url, params: { rank: valid_attributes }
        expect(response).to redirect_to(rank_url(Rank.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Rank" do
        expect {
          post ranks_url, params: { rank: invalid_attributes }
        }.to change(Rank, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post ranks_url, params: { rank: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested rank" do
        rank = Rank.create! valid_attributes
        patch rank_url(rank), params: { rank: new_attributes }
        rank.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the rank" do
        rank = Rank.create! valid_attributes
        patch rank_url(rank), params: { rank: new_attributes }
        rank.reload
        expect(response).to redirect_to(rank_url(rank))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        rank = Rank.create! valid_attributes
        patch rank_url(rank), params: { rank: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested rank" do
      rank = Rank.create! valid_attributes
      expect {
        delete rank_url(rank)
      }.to change(Rank, :count).by(-1)
    end

    it "redirects to the ranks list" do
      rank = Rank.create! valid_attributes
      delete rank_url(rank)
      expect(response).to redirect_to(ranks_url)
    end
  end
end
